application: bayesrss
version: 4-smart-fetch
runtime: python
api_version: 1

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: (/feeds|/feed/delete)
  script: main.py
  login: admin
  
- url: /feed.*
  script: main.py

- url: /
  script: main.py

