application: bayesrss
version: 1
runtime: python
api_version: 1

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: favicon.ico
  
- url: /feed.*
  script: main.py

